version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volume for MySQL data persistence
    networks:
      - networkmysql

  spring:
    image: ryadhlaabidi-5sim3-g1-kaddem
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springcontainer
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: kaddem
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8090:8080"
    depends_on:
      - mysql
    networks:
      - networkmysql

  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    environment:
      - DATA_SOURCE_NAME=root:root@(mysql:3306)/kaddem
    ports:
      - "9105:9104"  # Expose the metrics on port 9104
    networks:
      - networkmysql
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - /home/msi/.my.cnf:/cfg/.my.cnf  # Mount the .my.cnf file
    command:
      - --config.my-cnf=/cfg/.my.cnf  # Pass the path to the .my.cnf file inside the container

networks:
  networkmysql:
    driver: bridge

volumes:
  mysql_data:  # Volume for MySQL persistence
  mysql_exporter_data:  # Volume for MySQL Exporter persistence

