version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 0000         # Set your root password
      MYSQL_DATABASE: kaddem_db          # Create a database named kaddem_db
    ports:
      - "3306:3306"                      # Expose MySQL on port 3306
    networks:
      - my-network

  springboot:
    build:
      context: .                         # Path to your Spring Boot application
    ports:
      - "8081:8080"                      # Expose Spring Boot on port 8080
    depends_on:
      - mysql                            # Wait for MySQL to be ready before starting Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

